### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by dinosaw** [ahmedalsudani/sync-video#4]
Hi Ahmed!

First I want to tell you how great this application is. When running your demo site, it's **exactly** what I've been looking for out of a web application!

That being said, I'm having some issues getting it set up. I think it's due to Firebase changing / upgrading their services. Basically, when creating an application now in Firebase, it gives you the following information to use for your web app:

```
<script src="https://www.gstatic.com/firebasejs/3.6.3/firebase.js"></script>
<script>
  // Initialize Firebase
  var config = {
    apiKey: "AAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    authDomain: "dinosaw-things.firebaseapp.com",
    databaseURL: "https://dinosaw-things.firebaseio.com",
    storageBucket: "dinosaw-things.appspot.com",
    messagingSenderId: "412738834018"
  };
  firebase.initializeApp(config);
</script>
```

After looking through the source code of your working demo, the only scripts calling to Firebase that I can see are:

```
<script type="text/javascript" src="https://cdn.firebase.com/js/client/1.0.11/firebase.js"></script>
<script>
FIREBASE_ROOT = 'https://sync-video.firebaseio.com/demo/';
syncVideo(document.getElementsByClassName('sync-video')[0], 'alsudani-01');
</script>
```

What I attempted to do was simply replace your `FIREBASE_ROOT` with what Firebase provides to me as the `databaseURL`, using `https://dinosaw-things.firebaseio.com`. But the video player doesn't seem to be syncing between two different browsers / users after doing that.

Do you have any idea how I can make this application work with how Firebase works now? I would really, really, really love to have this! Thanks again for your work on this!

**Comment by ahmedalsudani** [comment]
Thanks for reporting this issue, @dinosaw. 

It is more than likely the firebase API has changed, so you will need to follow their instructions in order to create a Firebase object using the new API. 

I'm busy for the next couple of weeks and will take a look at how it can be done later this month. 

Cheers!

**Comment by dinosaw** [comment]
Thanks for the quick reply! I'll play around with Firebase and see if I can manage to figure it out on my own. But yeah, just whenever you have some time to look at it would be great - no rush! Again, this is the perfect web application.

**Comment by ahmedalsudani** [comment]
Hey @dinosaw,

There are two things that are possibly preventing your app from working:

- you are using a different Firebase version from the one in my demo.
- your Firebase database is probably "locked down"

To solve the first problem, you can either use the older version of Firebase that you could see in the demo, or figure out how to pass a Firebase object to the `syncVideo` function using the new API.

To solve the second problem, go to your Firebase database settings. Under rules, change the value to the following:

```
{
    "rules": {
        ".read": true,
        ".write": true
    }
}
```

That's a dirty solution that makes your database open to the world. If you would like to avoid it, you can read the [Firebase authentication docs](https://firebase.google.com/docs/auth/) and authenticate users.

I hope that helps you get it working.
